repos:
  - repo: local
    hooks:
      - id: soroban-versioning
        name: Send hash to Soroban contract before push
        language: python
        additional_dependencies:
          - soroban
        entry: python soroban_versioning_pre_push.py
        pass_filenames: false
        always_run: true
        stages:
          - pre-push