- id: soroban-versioning
  name: Send hash to Soroban contract before push
  language: python
  additional_dependencies:
    - soroban
  entry: python pre-push.py
  pass_filenames: false
  always_run: true
  stages:
    - pre-push