[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tansu"
version = "1.0.0"
dependencies = [
    "sqlalchemy",
    "psycopg[binary]",
    "pydantic",
    "pydantic-settings",
    "stellar-sdk",
]

[tool.hatch.build.targets.wheel]
packages = ["src/tansu"]
